spring.application.name=edumate

spring.datasource.url=jdbc:h2:file:./data/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

spring.sql.init.mode=always

spring.config.import=optional:file:.env[.properties]

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

logging.level.org.springframework.security.web.context=TRACE
logging.level.org.springframework.security.web.session=TRACE
