spring.application.name=edumate
spring.config.import=optional:file:.env[.properties]
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:mysql://localhost:3306/Edumatedb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.sql.init.mode=always

spring.config.import=optional:file:.env[.properties]

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=true

logging.level.org.springframework.security.web.context=TRACE
logging.level.org.springframework.security.web.session=TRACE

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
